[project]
name = "PySide Widgets Project"

[tool.pyside6-project]
files = ["AstroPictureHandler.py", "ClickableLabel.py", "FitsLibrary.py", "Picture.py", "biblio_images.ui", "form.ui", "mainwindow.py", "picture.ui", "style.qss"]
